import { Product, Category } from "@/lib";

export const categories: Category[] = [
    { id: "all", name: "Semua Produk", count: 48 },
    { id: "vitamins", name: "Vitamin & Suplemen", count: 12 },
    { id: "medication", name: "Obat-obatan", count: 18 },
    { id: "skincare", name: "Skincare", count: 8 },
    { id: "baby", name: "Ibu & Bayi", count: 6 },
    { id: "covid", name: "Perlindungan Covid", count: 4 },
];

export const products: Product[] = [
    {
        id: "1",
        name: "Blackmores Multivitamin Adults",
        brand: "Blackmores",
        category: "vitamins",
        price: 185000,
        originalPrice: 220000,
        rating: 4.8,
        reviewCount: 312,
        dosage: "60 Tablet",
        badge: "sale",
        inStock: true,
        description:
            "Formula multivitamin lengkap untuk mendukung kesehatan harian orang dewasa.",
        benefits: [
            "Meningkatkan imunitas",
            "Mendukung energi harian",
            "Kaya antioksidan",
        ],
    },
    {
        id: "2",
        name: "Vitamin C 1000mg Effervescent",
        brand: "Redoxon",
        category: "vitamins",
        price: 95000,
        rating: 4.6,
        reviewCount: 289,
        dosage: "30 Tablet",
        badge: "popular",
        inStock: true,
        description: "Vitamin C effervescent dengan rasa jeruk segar.",
        benefits: ["Meningkatkan daya tahan tubuh", "Antioksidan kuat"],
    },
    {
        id: "3",
        name: "Paracetamol 500mg",
        brand: "Sanmol",
        category: "medication",
        price: 28000,
        rating: 4.9,
        reviewCount: 1204,
        dosage: "10 Tablet",
        inStock: true,
        description: "Pereda nyeri dan penurun demam yang handal.",
    },
    {
        id: "4",
        name: "Amoxicillin 500mg",
        brand: "Kimia Farma",
        category: "medication",
        price: 45000,
        originalPrice: 55000,
        rating: 4.7,
        reviewCount: 567,
        dosage: "10 Kapsul",
        badge: "sale",
        inStock: true,
        description: "Antibiotik spektrum luas untuk infeksi bakteri.",
    },
    {
        id: "5",
        name: "Cetirizine 10mg Antihistamin",
        brand: "Hexpharm",
        category: "medication",
        price: 38000,
        rating: 4.5,
        reviewCount: 198,
        dosage: "10 Tablet",
        inStock: true,
        description: "Mengatasi alergi, bersin, dan gatal-gatal.",
    },
    {
        id: "6",
        name: "Omega-3 Fish Oil 1000mg",
        brand: "Nature's Plus",
        category: "vitamins",
        price: 210000,
        originalPrice: 260000,
        rating: 4.7,
        reviewCount: 423,
        dosage: "90 Kapsul",
        badge: "sale",
        inStock: true,
        description: "Suplemen minyak ikan untuk kesehatan jantung dan otak.",
        benefits: ["Kesehatan jantung", "Fungsi otak optimal", "Anti-inflamasi"],
    },
    {
        id: "7",
        name: "Sunscreen SPF 50+ PA++++",
        brand: "Skintific",
        category: "skincare",
        price: 125000,
        rating: 4.8,
        reviewCount: 887,
        badge: "new",
        inStock: true,
        description: "Perlindungan UV maksimal tanpa rasa berminyak.",
    },
    {
        id: "8",
        name: "Baby Lotion Gentle Care",
        brand: "Johnson's Baby",
        category: "baby",
        price: 65000,
        rating: 4.9,
        reviewCount: 2341,
        inStock: true,
        description: "Lotion lembut khusus untuk kulit bayi yang sensitif.",
    },
    {
        id: "9",
        name: "Masker Medis 3 Ply",
        brand: "ProMed",
        category: "covid",
        price: 45000,
        rating: 4.6,
        reviewCount: 3102,
        dosage: "50 pcs",
        inStock: true,
        description: "Masker medis 3 lapis standar WHO.",
    },
    {
        id: "10",
        name: "Probiotik Lacto-B",
        brand: "Nutricia",
        category: "vitamins",
        price: 78000,
        rating: 4.7,
        reviewCount: 445,
        dosage: "30 Sachet",
        badge: "popular",
        inStock: true,
        description: "Menjaga keseimbangan bakteri baik di usus.",
    },
    {
        id: "11",
        name: "Antangin JRG Herbal",
        brand: "Deltomed",
        category: "medication",
        price: 32000,
        rating: 4.4,
        reviewCount: 892,
        dosage: "12 Kapsul",
        inStock: true,
        description: "Obat masuk angin herbal tradisional.",
    },
    {
        id: "12",
        name: "Hyaluronic Acid Serum",
        brand: "Some By Mi",
        category: "skincare",
        price: 189000,
        originalPrice: 230000,
        rating: 4.8,
        reviewCount: 1123,
        badge: "sale",
        inStock: true,
        description: "Serum pelembap intensif dengan hyaluronic acid.",
    },
];

export const formatRupiah = (value: number): string => {
    return new Intl.NumberFormat("id-ID", {
        style: "currency",
        currency: "IDR",
        minimumFractionDigits: 0,
    }).format(value);
};